spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/companydb
    username: root
  jpa:
    hibernate:
      ddl-auto: update

welcome:
  message: 'welcome to dev'
